### ISSUE TITLE
Mer oversiktlig kaffenavn-liste ved å fokusere på kaffe vi faktisk har på lager

### ISSUE THREAD

**Issue by joabje** [magnusjerre/Kaffe#26]
I lista med kaffenavn begynner vi å få samlet mange kaffetyper og den øker stadig. Foreslår å gjøre den mer oversiktlig ved registrering av dagens kaffe/gjetting ved f eks å gruppere på om vi har kaffen tilgjengelig i kjøkkenskuffen eller ikke. 
Synes fortsatt det er flott at all kaffen vi har drukket siden starten er synlig.

**Comment by magnusjerre** [comment]
Hm, det burde vel gå relativt greit å få fikset. Tenker å lage en ekstra side der man kan få se litt mer informasjon om hver av kaffene vi har registrert, kan jo legge til en checkbox på hver av dem for om den skal inkluderes i dropdown listen eller ikke. Ka du tru?

**Comment by joabje** [comment]
Høres bra ut!
