### ISSUE TITLE
Drop down liste for gjetting på dagens kaffe

### ISSUE THREAD

**Issue by magnusjerre** [magnusjerre/Kaffe#4]
"Umulig" å gjette riktig kaffe dersom man ikke har noe å gjette blant, skrivemåte kan også være forskjellig

**Comment by joabje** [comment]
Vote! 
Samt samme ved registrering av dagens kaffe: Kun mulig å registrere dagens kaffe av en av "våre kaffetyper" ?

**Comment by magnusjerre** [comment]
Ja, det er nok lurt. Ny (admin?)side to the rescue! Eventuelt bare slenge det inn manuelt i databsen sånn midlertidig..
