### ISSUE TITLE
Terningkast 

### ISSUE THREAD

**Issue by BassOfLion** [magnusjerre/Kaffe#9]
Bytte ut score til å være terning (bilde) istedenfor å skrive score

**Comment by magnusjerre** [comment]
Da får vi færre karakterer å velge mellom da, men for min del er det helt greit

**Comment by joabje** [comment]
Vi gjør det kanskje litt på untappdmåten. Hva med å etter hvert illustrere det som hele og halve kaffekopper bortover på tilsvarende måte som untappd bruker ølkorker?

**Comment by magnusjerre** [comment]
Da ble løst ved hjelp av kaffebønner!
